// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONzl9kwNfrYbC92yh5ETqd73uMRW-ETk',
    appId: '1:727908876709:web:4eba967e1a92bb67c2284c',
    messagingSenderId: '727908876709',
    projectId: 'foodgo-64c08',
    authDomain: 'foodgo-64c08.firebaseapp.com',
    storageBucket: 'foodgo-64c08.firebasestorage.app',
    measurementId: 'G-G2YEWKCKVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVTA6pHlYx8BIrRfVwfY5pU2Il_n0eEsA',
    appId: '1:727908876709:android:aef51ee508c667c5c2284c',
    messagingSenderId: '727908876709',
    projectId: 'foodgo-64c08',
    storageBucket: 'foodgo-64c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDupgJAQlSvl_zTLBbvb4ashsKSIxN3cnM',
    appId: '1:727908876709:ios:8bbbda3c993a2723c2284c',
    messagingSenderId: '727908876709',
    projectId: 'foodgo-64c08',
    storageBucket: 'foodgo-64c08.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryandecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDupgJAQlSvl_zTLBbvb4ashsKSIxN3cnM',
    appId: '1:727908876709:ios:8bbbda3c993a2723c2284c',
    messagingSenderId: '727908876709',
    projectId: 'foodgo-64c08',
    storageBucket: 'foodgo-64c08.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryandecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCONzl9kwNfrYbC92yh5ETqd73uMRW-ETk',
    appId: '1:727908876709:web:4a1ae073cfaaceeec2284c',
    messagingSenderId: '727908876709',
    projectId: 'foodgo-64c08',
    authDomain: 'foodgo-64c08.firebaseapp.com',
    storageBucket: 'foodgo-64c08.firebasestorage.app',
    measurementId: 'G-8V9XK65FTM',
  );

}